version: '3'
services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 8001:80
    depends_on:
      - web
    volumes:
      - ./nginx/:/src/nginx/
      - static_volume:/env_root/static_root/
      - media_volume:/env_root/media_root/
    networks:
      - webblog
  web:
    build: .
    restart: always
    command: gunicorn ateam_backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/src/
      - static_volume:/env_root/static_root/
      - media_volume:/env_root/media_root/
    env_file:
      - ./.env
    networks:
      - webblog

volumes:
  static_volume:
  media_volume:

networks:
  webblog:
    external: true