# Generated by Django 3.2.9 on 2021-11-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=60, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField(max_length=2000)),
                ('cover_image_url', models.URLField(blank=True, max_length=250)),
                ('cover_intro', models.TextField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
