# Generated by Django 3.2.9 on 2021-11-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
