# Generated by Django 3.2.9 on 2021-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_artikel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
