# Generated by Django 3.2.9 on 2021-11-18 08:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_artikel_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='extda',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
