# Generated by Django 3.2.9 on 2021-11-18 09:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_artikel_extda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='extda',
        ),
        migrations.AlterField(
            model_name='artikel',
            name='content',
            field=tinymce.models.HTMLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='cover_intro',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
