# Generated by Django 3.2.9 on 2021-11-18 23:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0005_auto_20211118_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='cover_intro',
            field=tinymce.models.HTMLField(max_length=1000),
        ),
    ]
