# Generated by Django 3.2.9 on 2021-11-23 05:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0006_alter_artikel_cover_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='cover_intro',
            field=tinymce.models.HTMLField(blank=True, max_length=1000),
        ),
    ]
